apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scope.fullname" . }}-webhook-cert-sa
  labels:
  {{- include "scope.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scope-cert-sa
  labels:
  {{- include "scope.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scope
  labels:
    app: scope
  {{- include "scope.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: scope
    {{- include "scope.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: scope
      {{- include "scope.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -c
        - /usr/local/bin/scope k8s
          {{- if .Values.config.criblDestination }}
          --cribldest {{ .Values.config.criblDestination }}
          {{- end }}
          {{- if .Values.config.metricDestination }}
          --metricdest {{ .Values.config.metricDestination }}
          --metricformat {{ .Values.config.metricFormat }}
          {{- end }}
          {{- if .Values.config.eventDestination }}
          --eventdest {{ .Values.config.eventDestination }}
          {{- end }}
          --server || sleep 1000
        command:
        - /bin/bash
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: scope
        ports:
        {{-  range .Values.service.ports }}
        - containerPort: {{ .targetPort }}
          protocol: {{ .protocol }}
        {{- end }}
        resources: {}
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
          readOnly: true
      serviceAccountName: {{ include "scope.fullname" . }}-cert-sa
      volumes:
      - name: certs
        secret:
          secretName: scope-secret
