apiVersion: v2
name: appscope
description: Deployment of AppScope in K8s.
type: application
version: 1.3.2
appVersion: 1.3.2
icon: https://michalbiesek.github.io/helm-charts/images/Cribl_Logo_Color_TM.png
